[package]
name = "test2"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }

# tonic
tonic = "0.14"
prost = "0.14"

tokio-util = "0.7"
tonic-prost = "0.14"

[build-dependencies]
# tonic-build = "0.13"
tonic-prost-build = "0.14"
walkdir = "2"